### ISSUE TITLE
HPXML Generation Error

### ISSUE THREAD

**Issue by lukeduran** [RadiantLabs/modeling-api-docs#42]
I believe that we previously faced [an issue very similar to this](https://github.com/RadiantLabs/modeling-api-docs/issues/27), but I'm creating a new issue because we are still facing this quite a bit - unsure if they are related. Below is both a request and the response we received. I have at least 14 of these that I can share if it would be helpful.

```{
    "request": {
        "headers": {
            "User-Agent": "python-requests/2.28.1",
            "Accept-Encoding": "gzip, deflate",
            "Accept": "*/*",
            "Connection": "keep-alive",
            "Content-Type": "application/json",
            "Authorization": "Bearer jqnTR0wR6nmnS6u5mLEm1NSXq1kHSaF16LYlInbQ8tC04QHa",
            "Content-Length": "934"
        },
        "body": {
            "addressFull": "345 Oglethorpe St NE, Washington, DC 20011-1635",
            "addressComponents": {
                "addressLine1": "345 Oglethorpe St NE",
                "city": "Washington",
                "stateAbbreviation": "DC",
                "zipCode": "20011-1635"
            },
            "baseBuilding": {
                "buildingSummary": {
                    "yearBuilt": 1960,
                    "bedroomsCount": 3,
                    "averageCeilingHeight": 8,
                    "conditionedFloorArea": 985
                },
                "enclosure": {
                    "airInfiltration": {
                        "rate": 1018,
                        "rateUnit": "CFM"
                    },
                    "attics": [
                        {
                            "floorAssemblyEffectiveRValue": 49,
                            "id": "attic-insulation-1"
                        }
                    ]
                }
            },
            "globalControls": {
                "debug": true,
                "includeInputs": true,
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "resolution": [
                    "annual",
                    "monthly"
                ],
                "timelineStartDate": "2024-02-27",
                "timelineDurationInYears": 1,
                "units": {
                    "energyStandard": "MBtu",
                    "coal": "metric ton",
                    "electricity": "MBtu",
                    "fuelOil": "MBtu",
                    "naturalGas": "MBtu",
                    "propane": "MBtu",
                    "woodCord": "MBtu",
                    "woodPellets": "MBtu",
                    "monetary": "USD",
                    "emissions": "CO2"
                }
            }
        }
    },
    "response": {
        "headers": {
            "Server": "nginx/1.24.0",
            "Date": "Tue, 27 Feb 2024 16:29:35 GMT",
            "Content-Type": "application/json;charset=utf-8",
            "Content-Length": "2446",
            "Connection": "keep-alive",
            "X-Request-Id": "01hqnp5xs93z0h6b1tdskc1wgb",
            "Strict-Transport-Security": "max-age=31536000"
        },
        "body": {
            "globalControls": {
                "timelineStartDate": "2024-02-27",
                "debug": true,
                "includeInputs": true,
                "resolution": [
                    "monthly",
                    "annual"
                ],
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "timelineDurationInYears": 1,
                "units": {
                    "monetary": "USD",
                    "electricity": "MBtu",
                    "naturalGas": "MBtu",
                    "woodPellets": "MBtu",
                    "propane": "MBtu",
                    "coal": "metric ton",
                    "emissions": "CO2",
                    "woodCord": "MBtu",
                    "energyStandard": "MBtu",
                    "fuelOil": "MBtu"
                }
            },
            "addressFull": "345 Oglethorpe St NE, Washington, DC 20011-1635",
            "baseBuilding": {
                "enclosure": {
                    "airInfiltration": {
                        "rate": 1018,
                        "rateUnit": "CFM"
                    },
                    "attics": [
                        {
                            "floorAssemblyEffectiveRValue": 49,
                            "id": "attic-insulation-1"
                        }
                    ]
                },
                "buildingSummary": {
                    "conditionedFloorArea": 985,
                    "yearBuilt": 1960,
                    "bedroomsCount": 3,
                    "averageCeilingHeight": 8
                }
            },
            "addressComponents": {
                "zipCode": "20011-1635",
                "addressLine1": "345 Oglethorpe St NE",
                "stateAbbreviation": "DC",
                "city": "Washington"
            },
            "errors": [
                {
                    "message": "\"+ node ./dist/cli-generate-hpxml-files.js --rowPath /tmp/modeling-api/dir1/2024022716254874581930/142879069_modified.json --outputDir /tmp/modeling-api/dir2/NORMAL/2024022716254874581930 --dataVersion radiantV5 --defaultsVersion 2.4.0 --hpxmlVersion 3.0.0 --disableSchematron --modelingInputsPath /tmp/modeling-api/dir1/2024022716254874581930/142879069_modeling_inputs.json --packageIds AUTOMATED_MEASURES --automatedMeasuresPath /tmp/modeling-api/dir1/2024022716254874581930/142879069_automated_measures.json --debug\\n{\\\"code\\\":3,\\\"error\\\":\\\"Could not find max option lookup. AHS Region: DC, District Of Columbia County\\\",\\\"stack\\\":\\\"Error: Could not find max option lookup. AHS Region: DC, District Of Columbia County\\\\n    at solveForDep (/app/dist/utils/lookup-defaults.js:117:15)\\\\n    at /app/dist/utils/lookup-defaults.js:39:63\\\\n    at arrayMap (/app/node_modules/lodash/lodash.js:653:23)\\\\n    at Function.map (/app/node_modules/lodash/lodash.js:9622:14)\\\\n    at recursiveLookup (/app/dist/utils/lookup-defaults.js:39:40)\\\\n    at lookupDefaults (/app/dist/utils/lookup-defaults.js:31:31)\\\\n    at generateBaseInputs (/app/dist/generate-hpxml/radiantV5-hpxml300-defaults240/generate-base-inputs.js:16:68)\\\\n    at genRadiantV5Hpxml300Defaults240 (/app/dist/generate-hpxml/radiantV5-hpxml300-defaults240/index.js:37:70)\\\\n    at generateHpxml (/app/dist/generate-hpxml/index.js:25:89)\\\\n    at generateHpxmlAndSaveToFile (/app/dist/cli-generate-hpxml-files.js:100:67)\\\"}\"",
                    "code": "error-generating-hpxml"
                }
            ]
        }
    }
}```

**Comment by kloconnell** [comment]
The error in this ticket is specific to Washington, DC. There are several other regions that would result in this same issue. The solution is drafted and in the queue for implementation behind a couple other more important issues.

**Comment by kloconnell** [comment]
This request is passing in our v2.0.0 development environment.
