### ISSUE TITLE
Sum of floor/slab area adjacent to conditioned space error

### ISSUE THREAD

**Issue by lukeduran** [RadiantLabs/modeling-api-docs#46]
We received this error and don't know what it means or how we can fix it. Can you provide insight?

```{
    "request": {
        "headers": {
            "User-Agent": "python-requests/2.28.1",
            "Accept-Encoding": "gzip, deflate",
            "Accept": "*/*",
            "Connection": "keep-alive",
            "Content-Type": "application/json",
            "Authorization": "Bearer jqnTR0wR6nmnS6u5mLEm1NSXq1kHSaF16LYlInbQ8tC04QHa",
            "Content-Length": "955"
        },
        "body": {
            "addressFull": "1240 NEOLA CHURCH RD, Stroudsburg, PA 18360",
            "addressComponents": {
                "addressLine1": "1240 NEOLA CHURCH RD",
                "city": "Stroudsburg",
                "stateAbbreviation": "PA",
                "zipCode": "18360"
            },
            "baseBuilding": {
                "buildingSummary": {
                    "yearBuilt": 1987
                },
                "systems": {
                    "hvac": {
                        "hvacHeatPumps": [
                            {
                                "systemType": "mini-split",
                                "heatLoadFraction": 1.0,
                                "coolLoadFraction": 1.0,
                                "heatEfficiency": 9.8,
                                "coolEfficiency": 19.2,
                                "compressorType": "single stage",
                                "backupSystem": {},
                                "id": "heat-pump-systems-1"
                            }
                        ]
                    }
                }
            },
            "globalControls": {
                "debug": true,
                "includeInputs": true,
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "resolution": [
                    "annual",
                    "monthly"
                ],
                "timelineStartDate": "2024-02-27",
                "timelineDurationInYears": 1,
                "units": {
                    "energyStandard": "MBtu",
                    "coal": "metric ton",
                    "electricity": "MBtu",
                    "fuelOil": "MBtu",
                    "naturalGas": "MBtu",
                    "propane": "MBtu",
                    "woodCord": "MBtu",
                    "woodPellets": "MBtu",
                    "monetary": "USD",
                    "emissions": "CO2"
                }
            }
        }
    },
    "response": {
        "headers": {
            "Server": "nginx/1.24.0",
            "Date": "Tue, 27 Feb 2024 16:25:45 GMT",
            "Content-Type": "application/json;charset=utf-8",
            "Content-Length": "3881",
            "Connection": "keep-alive",
            "X-Request-Id": "01hqnnzw89arq6q647yxdpbdr1",
            "Strict-Transport-Security": "max-age=31536000"
        },
        "body": {
            "globalControls": {
                "timelineStartDate": "2024-02-27",
                "debug": true,
                "includeInputs": true,
                "resolution": [
                    "monthly",
                    "annual"
                ],
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "timelineDurationInYears": 1,
                "units": {
                    "monetary": "USD",
                    "electricity": "MBtu",
                    "naturalGas": "MBtu",
                    "woodPellets": "MBtu",
                    "propane": "MBtu",
                    "coal": "metric ton",
                    "emissions": "CO2",
                    "woodCord": "MBtu",
                    "energyStandard": "MBtu",
                    "fuelOil": "MBtu"
                }
            },
            "addressFull": "1240 NEOLA CHURCH RD, Stroudsburg, PA 18360",
            "baseBuilding": {
                "systems": {
                    "hvac": {
                        "hvacHeatPumps": [
                            {
                                "heatLoadFraction": 1.0,
                                "heatEfficiency": 9.8,
                                "backupSystem": {},
                                "coolLoadFraction": 1.0,
                                "coolEfficiency": 19.2,
                                "systemType": "mini-split",
                                "id": "heat-pump-systems-1",
                                "compressorType": "single stage"
                            }
                        ]
                    }
                },
                "buildingSummary": {
                    "yearBuilt": 1987
                }
            },
            "addressComponents": {
                "zipCode": "18360",
                "addressLine1": "1240 NEOLA CHURCH RD",
                "stateAbbreviation": "PA",
                "city": "Stroudsburg"
            },
            "errors": [
                {
                    "message": "[\"Info: Wrote file: /tmp/modeling-api/dir3/BASE/20240227162229899000505/run/in.xml\" \"Warning: No dishwasher specified, the model will not include dishwasher energy use.\" \"Warning: '/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/../weather/USA_PA_Allentown-Lehigh.Valley.Intl.AP.725170_TMY3-cache.csv' could not be found; regenerating it.\" \"Warning: Assembly R-value (0.7) for 'RimJoistBasementConditioned1Exposed:0' below minimum expected value. Construction R-value increased to 2.3.\" \"Warning: Assembly R-value (0.7) for 'RimJoistBasementConditioned1Exposed:90' below minimum expected value. Construction R-value increased to 2.3.\" \"Warning: Assembly R-value (0.7) for 'RimJoistBasementConditioned1Exposed:180' below minimum expected value. Construction R-value increased to 2.3.\" \"Warning: Assembly R-value (0.7) for 'RimJoistBasementConditioned1Exposed:270' below minimum expected value. Construction R-value increased to 2.3.\" \"Warning: Assembly R-value (0.7) for 'FloorAboveBasementConditioned1' below minimum expected value. Construction R-value increased to 1.85.\" \"Warning: Assembly R-value (0.7) for 'FoundationWallBasementConditioned1Exposed' below minimum expected value. Construction R-value increased to 1.32.\" \"Error: Sum of floor/slab area adjacent to conditioned space (1846.0) is greater than conditioned floor area (1300.0).\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/measure.rb:1608:in `add_conditioned_floor_area'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/measure.rb:239:in `create'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/measure.rb:118:in `run'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:289:in `run_measure'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:147:in `block (2 levels) in apply_measures'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:139:in `each'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:139:in `block in apply_measures'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:134:in `each'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:134:in `apply_measures'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:22:in `run_hpxml_workflow'\" \"/var/bin/OpenStudio-HPXML/workflow/run_simulation.rb:40:in `run_workflow'\" \"/var/bin/OpenStudio-HPXML/workflow/run_simulation.rb:157:in `<top (required)>'\" \"eval:121:in `require'\" \"eval:121:in `require'\" \":/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'\" \":/openstudio_cli.rb:1518:in `execute'\" \":/openstudio_cli.rb:761:in `execute'\" \":/openstudio_cli.rb:1755:in `<main>'\" \"eval:175:in `eval'\" \"eval:175:in `require_embedded_absolute'\" \"eval:160:in `block in require_embedded'\" \"eval:154:in `each'\" \"eval:154:in `require_embedded'\" \"eval:113:in `require'\" \"eval:3:in `<main>'\"]",
                    "code": "openstudio-creating-input-unsuccessful"
                }
            ]
        }
    }
}```

**Comment by lukeduran** [comment]
We are still getting several of these errors @kellyatradiantlabs @joshuamzm . Can you please explain this error and how we can get past it?

**Comment by kloconnell** [comment]
Hi @lukeduran - thanks for following up on this issue. This is something that we've been working on for the past two weeks. It has to do with the geometries of the the building floor and foundation based on the data pulled from our vendors. We're working to update our assumptions to better handle certain cases like this address. In the meantime, I'd recommend the best way to work around this error is to specify the `buildingsummary.conditionedFloorArea` and `enclosure.foundations.area` in your request.

**Comment by lukeduran** [comment]
@kellyatradiantlabs will this be resolved in v2?

**Comment by kloconnell** [comment]
@lukeduran yes it will! I just added the tag.

**Comment by kloconnell** [comment]
This request is now passing in our v2.0.0 development environment.
