### ISSUE TITLE
Water Heater Efficiency > 1

### ISSUE THREAD

**Issue by kloconnell** [RadiantLabs/modeling-api-docs#54]
**Request:**
```
{
            "addressFull": "7 Goldenrod Ln, Marlton, NJ 08053-5549",
            "addressComponents": {
                "addressLine1": "7 Goldenrod Ln",
                "city": "Marlton",
                "stateAbbreviation": "NJ",
                "zipCode": "08053-5549"
            },
            "baseBuilding": {
                "buildingSummary": {
                    "yearBuilt": 1999,
                    "bedroomsCount": 2,
                    "averageCeilingHeight": 9,
                    "conditionedFloorArea": 2028
                },
                "enclosure": {
                    "airInfiltration": {
                        "rate": 1784,
                        "rateUnit": "CFM"
                    },
                    "attics": [
                        {
                            "floorAssemblyEffectiveRValue": 52,
                            "id": "attic-insulation-1"
                        },
                        {
                            "floorAssemblyEffectiveRValue": 19,
                            "id": "attic-insulation-2"
                        }
                    ],
                    "foundations": [
                        {
                            "id": "floor-and-foundation-insulation-1"
                        }
                    ],
                    "walls": [
                        {
                            "assemblyEffectiveRValue": 13,
                            "id": "wall-insulation-1"
                        }
                    ]
                },
                "systems": {
                    "hvac": {
                        "hvacHeatingSystems": [
                            {
                                "systemType": "furnace",
                                "fuel": "natural gas",
                                "heatLoadFraction": 1.0,
                                "heatEfficiency": 0.96,
                                "heatEfficiencyUnits": "AFUE",
                                "id": "heating-systems-1"
                            }
                        ],
                        "hvacCoolingSystems": [
                            {
                                "systemType": "central air conditioner",
                                "coolLoadFraction": 1.0,
                                "coolEfficiency": 15.0,
                                "coolEfficiencyUnits": "SEER",
                                "compressorType": "single stage",
                                "id": "cooling-systems-1"
                            }
                        ]
                    },
                    "waterHeating": {
                        "waterHeatingSystems": [
                            {
                                "fuel": "natural gas",
                                "dhwLoadFraction": 1.0,
                                "id": "water-heating-1",
                                "energyFactor": 0.95
                            }
                        ]
                    }
                }
            },
            "globalControls": {
                "debug": true,
                "includeInputs": true,
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "resolution": [
                    "annual",
                    "monthly"
                ],
                "timelineStartDate": "2024-03-21",
                "timelineDurationInYears": 1,
                "units": {
                    "energyStandard": "MBtu",
                    "coal": "metric ton",
                    "electricity": "MBtu",
                    "fuelOil": "MBtu",
                    "naturalGas": "MBtu",
                    "propane": "MBtu",
                    "woodCord": "MBtu",
                    "woodPellets": "MBtu",
                    "monetary": "USD",
                    "emissions": "CO2"
                }
            }
        }
```

**Response:**
```
{
    "globalControls": {
        "timelineStartDate": "2024-03-21",
        "debug": true,
        "includeInputs": true,
        "resolution": [
            "monthly",
            "annual"
        ],
        "includeBase": true,
        "includeTypical": true,
        "useFixture": false,
        "timelineDurationInYears": 1,
        "units": {
            "monetary": "USD",
            "electricity": "MBtu",
            "naturalGas": "MBtu",
            "woodPellets": "MBtu",
            "propane": "MBtu",
            "coal": "metric ton",
            "emissions": "CO2",
            "woodCord": "MBtu",
            "energyStandard": "MBtu",
            "fuelOil": "MBtu"
        }
    },
    "addressFull": "7 Goldenrod Ln, Marlton, NJ 08053-5549",
    "baseBuilding": {
        "systems": {
            "waterHeating": {
                "waterHeatingSystems": [
                    {
                        "dhwLoadFraction": 1.0,
                        "fuel": "natural gas",
                        "energyFactor": 0.95,
                        "id": "water-heating-1"
                    }
                ]
            },
            "hvac": {
                "hvacHeatingSystems": [
                    {
                        "heatLoadFraction": 1.0,
                        "heatEfficiency": 0.96,
                        "fuel": "natural gas",
                        "systemType": "furnace",
                        "id": "heating-systems-1",
                        "heatEfficiencyUnits": "AFUE"
                    }
                ],
                "hvacCoolingSystems": [
                    {
                        "coolEfficiencyUnits": "SEER",
                        "coolLoadFraction": 1.0,
                        "coolEfficiency": 15.0,
                        "systemType": "central air conditioner",
                        "id": "cooling-systems-1",
                        "compressorType": "single stage"
                    }
                ]
            }
        },
        "enclosure": {
            "airInfiltration": {
                "rate": 1784,
                "rateUnit": "CFM"
            },
            "walls": [
                {
                    "assemblyEffectiveRValue": 13,
                    "id": "wall-insulation-1"
                }
            ],
            "foundations": [
                {
                    "id": "floor-and-foundation-insulation-1"
                }
            ],
            "attics": [
                {
                    "floorAssemblyEffectiveRValue": 52,
                    "id": "attic-insulation-1"
                },
                {
                    "floorAssemblyEffectiveRValue": 19,
                    "id": "attic-insulation-2"
                }
            ]
        },
        "buildingSummary": {
            "conditionedFloorArea": 2028,
            "yearBuilt": 1999,
            "bedroomsCount": 2,
            "averageCeilingHeight": 9
        }
    },
    "addressComponents": {
        "zipCode": "08053-5549",
        "addressLine1": "7 Goldenrod Ln",
        "stateAbbreviation": "NJ",
        "city": "Marlton"
    },
    "errors": [
        {
            "message": "[\"Info: Wrote file: /tmp/modeling-api/openstudio-outputs/BASE/01htmxp94d3jjvdg0kxfkwh9fq/run/in.xml\" \"Warning: No dishwasher specified, the model will not include dishwasher energy use.\" \"Warning: Assembly R-value (0.7) for 'RimJoistfloor-and-foundation-insulation-1Exposed:0' below minimum expected value. Construction R-value increased to 2.3.\" \"Warning: Assembly R-value (0.7) for 'RimJoistfloor-and-foundation-insulation-1Exposed:90' below minimum expected value. Construction R-value increased to 2.3.\" \"Warning: Assembly R-value (0.7) for 'RimJoistfloor-and-foundation-insulation-1Exposed:180' below minimum expected value. Construction R-value increased to 2.3.\" \"Warning: Assembly R-value (0.7) for 'RimJoistfloor-and-foundation-insulation-1Exposed:270' below minimum expected value. Construction R-value increased to 2.3.\" \"Warning: Assembly R-value (0.7) for 'FoundationWallfloor-and-foundation-insulation-1Exposed' below minimum expected value. Construction R-value increased to 1.32.\" \"Error: A water heater heat source (either burner or element) efficiency of > 1 has been calculated, double check water heater inputs.\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/waterheater.rb:1504:in `calc_tank_UA'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/waterheater.rb:21:in `apply_tank'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/measure.rb:1957:in `block in add_hot_water_and_appliances'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/measure.rb:1950:in `each'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/measure.rb:1950:in `add_hot_water_and_appliances'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/measure.rb:259:in `create'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/measure.rb:118:in `run'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:289:in `run_measure'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:147:in `block (2 levels) in apply_measures'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:139:in `each'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:139:in `block in apply_measures'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:134:in `each'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:134:in `apply_measures'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:22:in `run_hpxml_workflow'\" \"/var/bin/OpenStudio-HPXML/workflow/run_simulation.rb:40:in `run_workflow'\" \"/var/bin/OpenStudio-HPXML/workflow/run_simulation.rb:157:in `<top (required)>'\" \"eval:121:in `require'\" \"eval:121:in `require'\" \":/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'\" \":/openstudio_cli.rb:1518:in `execute'\" \":/openstudio_cli.rb:761:in `execute'\" \":/openstudio_cli.rb:1755:in `<main>'\" \"eval:175:in `eval'\" \"eval:175:in `require_embedded_absolute'\" \"eval:160:in `block in require_embedded'\" \"eval:154:in `each'\" \"eval:154:in `require_embedded'\" \"eval:113:in `require'\" \"eval:3:in `<main>'\"]",
            "code": "openstudio-creating-input-unsuccessful"
        }
    ]
}
```

**Comment by kloconnell** [comment]
Due to some breaking changes in v2.0.0, the request in this ticket is not longer valid, but with some slight tweaks to align schemas, this bug is now resolved in our development environment. Note that in the `waterHeatingSystems` object, `systemType` is a required field and fields `energyFactor` and `uniformEnergyFactor` have been renamed to `efficiency` and `efficiencyUnits`.
```
"waterHeatingSystems": [
                            {
                                "fuel": "natural gas",
                                "dhwLoadFraction": 1.0,
                                "id": "water-heating-1",
                                "efficiency": 0.95,
                                "efficiencyUnits": "EF",
                                "systemType": "storage water heater"
                            }
```
