### ISSUE TITLE
Row is miss a required value for: AREA_PROPERTY

### ISSUE THREAD

**Issue by lukeduran** [RadiantLabs/modeling-api-docs#58]
This error gives me the sense that it thinks we are missing a "required" attribute for an object, but it's hard for me to tell what it's referring to. Can you provide insight?

**Example**

```{
    "request": {
        "headers": {
            "User-Agent": "python-requests/2.28.1",
            "Accept-Encoding": "gzip, deflate",
            "Accept": "*/*",
            "Connection": "keep-alive",
            "Content-Type": "application/json",
            "Authorization": "Bearer jqnTR0wR6nmnS6u5mLEm1NSXq1kHSaF16LYlInbQ8tC04QHa",
            "Content-Length": "1073"
        },
        "body": {
            "addressFull": "11230 S Morrice Rd, Morrice, MI 48857-9786",
            "addressComponents": {
                "addressLine1": "11230 S Morrice Rd",
                "city": "Morrice",
                "stateAbbreviation": "MI",
                "zipCode": "48857-9786"
            },
            "baseBuilding": {
                "systems": {
                    "hvac": {
                        "hvacHeatingSystems": [
                            {
                                "systemType": "furnace",
                                "fuel": "natural gas",
                                "heatLoadFraction": 1.0,
                                "heatEfficiency": 0.96,
                                "heatEfficiencyUnits": "AFUE",
                                "id": "heating-systems-1"
                            }
                        ],
                        "hvacCoolingSystems": [
                            {
                                "systemType": "central air conditioner",
                                "coolLoadFraction": 1.0,
                                "coolEfficiency": 17.0,
                                "coolEfficiencyUnits": "SEER",
                                "compressorType": "single stage",
                                "id": "cooling-systems-1"
                            }
                        ]
                    }
                }
            },
            "globalControls": {
                "debug": true,
                "includeInputs": true,
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "resolution": [
                    "annual",
                    "monthly"
                ],
                "timelineStartDate": "2024-04-08",
                "timelineDurationInYears": 1,
                "units": {
                    "energyStandard": "MBtu",
                    "coal": "metric ton",
                    "electricity": "MBtu",
                    "fuelOil": "MBtu",
                    "naturalGas": "MBtu",
                    "propane": "MBtu",
                    "woodCord": "MBtu",
                    "woodPellets": "MBtu",
                    "monetary": "USD",
                    "emissions": "CO2"
                }
            }
        }
    },
    "response": {
        "headers": {
            "Server": "nginx/1.24.0",
            "Date": "Mon, 08 Apr 2024 20:33:11 GMT",
            "Content-Type": "application/json;charset=utf-8",
            "Content-Length": "2537",
            "Connection": "keep-alive",
            "X-Request-Id": "01htzpma7w796xqd7zyvcz0cwm",
            "Strict-Transport-Security": "max-age=31536000"
        },
        "body": {
            "globalControls": {
                "timelineStartDate": "2024-04-08",
                "debug": true,
                "includeInputs": true,
                "resolution": [
                    "monthly",
                    "annual"
                ],
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "timelineDurationInYears": 1,
                "units": {
                    "monetary": "USD",
                    "electricity": "MBtu",
                    "naturalGas": "MBtu",
                    "woodPellets": "MBtu",
                    "propane": "MBtu",
                    "coal": "metric ton",
                    "emissions": "CO2",
                    "woodCord": "MBtu",
                    "energyStandard": "MBtu",
                    "fuelOil": "MBtu"
                }
            },
            "addressFull": "11230 S Morrice Rd, Morrice, MI 48857-9786",
            "baseBuilding": {
                "systems": {
                    "hvac": {
                        "hvacHeatingSystems": [
                            {
                                "heatLoadFraction": 1.0,
                                "heatEfficiency": 0.96,
                                "fuel": "natural gas",
                                "systemType": "furnace",
                                "id": "heating-systems-1",
                                "heatEfficiencyUnits": "AFUE"
                            }
                        ],
                        "hvacCoolingSystems": [
                            {
                                "coolEfficiencyUnits": "SEER",
                                "coolLoadFraction": 1.0,
                                "coolEfficiency": 17.0,
                                "systemType": "central air conditioner",
                                "id": "cooling-systems-1",
                                "compressorType": "single stage"
                            }
                        ]
                    }
                }
            },
            "addressComponents": {
                "zipCode": "48857-9786",
                "addressLine1": "11230 S Morrice Rd",
                "stateAbbreviation": "MI",
                "city": "Morrice"
            },
            "errors": [
                {
                    "message": "\"+ node ./dist/cli-generate-hpxml-files.js --rowPath /tmp/modeling-api/hpxml-gen-inputs/01htzpma7w796xqd7zyvcz0cwm/220736635.json --outputDir /tmp/modeling-api/hpxml-gen-outputs/NORMAL/01htzpma7w796xqd7zyvcz0cwm --dataVersion radiantV5 --defaultsVersion 2.4.0 --hpxmlVersion 3.0.0 --modelingInputsPath /tmp/modeling-api/hpxml-gen-inputs/01htzpma7w796xqd7zyvcz0cwm/220736635_modeling_inputs.json --packageIds AUTOMATED_MEASURES --automatedMeasuresPath /tmp/modeling-api/hpxml-gen-inputs/01htzpma7w796xqd7zyvcz0cwm/220736635_automated_measures.json --disableSchematron --debug\\n{\\\"code\\\":3,\\\"error\\\":\\\"Row is missing a required value for: AREA_PROPERTY\\\",\\\"stack\\\":\\\"Error: Row is missing a required value for: AREA_PROPERTY\\\\n    at /app/dist/utils/check-incoming-required-values.js:20:19\\\\n    at /app/node_modules/lodash/lodash.js:4967:15\\\\n    at baseForOwn (/app/node_modules/lodash/lodash.js:3032:24)\\\\n    at /app/node_modules/lodash/lodash.js:4936:18\\\\n    at Function.forEach (/app/node_modules/lodash/lodash.js:9410:14)\\\\n    at checkIncomingRequiredValues (/app/dist/utils/check-incoming-required-values.js:18:22)\\\\n    at genRadiantV5Hpxml300Defaults240 (/app/dist/generate-hpxml/radiantV5-hpxml300-defaults240/index.js:31:70)\\\\n    at generateHpxml (/app/dist/generate-hpxml/index.js:25:89)\\\\n    at generateHpxmlAndSaveToFile (/app/dist/cli-generate-hpxml-files.js:100:67)\\\\n    at /app/dist/cli-generate-hpxml-files.js:174:5\\\"}\"",
                    "code": "error-generating-hpxml"
                }
            ]
        }
    }
}
```

**Comment by kloconnell** [comment]
@lukeduran AREA_PROPERTY is the equivalent of `conditionedFloorArea`. This error means that our vendor data did not have a square footage reported for the property. The way to workaround this error is to include `conditionedFloorArea` in your request. For this specific address, the vendor data is also missing `yearBuilt` and will thus hit the error in #59 instead if `conditionedFloorArea` is included.

**Comment by kloconnell** [comment]
We revised the error message for this type of error in v2.0.0 to be more clear:
```
    "errors": [
        {
            "message": "Gathered property information is insufficient, try providing a value for conditionedFloorArea",
            "code": "insufficient-data"
        }
]
```
