### ISSUE TITLE
Row is missing a required value for: YEAR_BUILT

### ISSUE THREAD

**Issue by lukeduran** [RadiantLabs/modeling-api-docs#59]
This one is odd particularly because the year built has been provided in this case so I can't really figure out how else to remedy this. I also didn't think that Year Built was required.

**Example**

```{
    "request": {
        "headers": {
            "User-Agent": "python-requests/2.28.1",
            "Accept-Encoding": "gzip, deflate",
            "Accept": "*/*",
            "Connection": "keep-alive",
            "Content-Type": "application/json",
            "Authorization": "Bearer jqnTR0wR6nmnS6u5mLEm1NSXq1kHSaF16LYlInbQ8tC04QHa",
            "Content-Length": "1459"
        },
        "body": {
            "addressFull": "32861 E Carteret Ct, Millsboro, DE 19966-4829",
            "addressComponents": {
                "addressLine1": "32861 E Carteret Ct",
                "city": "Millsboro",
                "stateAbbreviation": "DE",
                "zipCode": "19966-4829"
            },
            "baseBuilding": {
                "buildingSummary": {
                    "yearBuilt": 1982,
                    "bedroomsCount": 3,
                    "averageCeilingHeight": 10,
                    "conditionedFloorArea": 2400
                },
                "enclosure": {
                    "airInfiltration": {
                        "rate": 886,
                        "rateUnit": "CFM"
                    },
                    "attics": [
                        {
                            "floorAssemblyEffectiveRValue": 30,
                            "id": "attic-insulation-1"
                        }
                    ],
                    "foundations": [
                        {
                            "type": "crawl vented",
                            "id": "floor-and-foundation-insulation-1"
                        },
                        {
                            "type": "crawl vented",
                            "id": "floor-and-foundation-insulation-2"
                        }
                    ],
                    "walls": [
                        {
                            "assemblyEffectiveRValue": 19,
                            "id": "wall-insulation-1"
                        }
                    ]
                },
                "systems": {
                    "hvac": {
                        "hvacHeatingSystems": [],
                        "hvacCoolingSystems": [
                            {
                                "systemType": "central air conditioner",
                                "coolLoadFraction": 1.0,
                                "coolEfficiency": 18.0,
                                "coolEfficiencyUnits": "SEER",
                                "compressorType": "single stage",
                                "id": "cooling-systems-1"
                            }
                        ]
                    },
                    "waterHeating": {
                        "waterHeatingSystems": []
                    }
                }
            },
            "globalControls": {
                "debug": true,
                "includeInputs": true,
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "resolution": [
                    "annual",
                    "monthly"
                ],
                "timelineStartDate": "2024-04-08",
                "timelineDurationInYears": 1,
                "units": {
                    "energyStandard": "MBtu",
                    "coal": "metric ton",
                    "electricity": "MBtu",
                    "fuelOil": "MBtu",
                    "naturalGas": "MBtu",
                    "propane": "MBtu",
                    "woodCord": "MBtu",
                    "woodPellets": "MBtu",
                    "monetary": "USD",
                    "emissions": "CO2"
                }
            }
        }
    },
    "response": {
        "headers": {
            "Server": "nginx/1.24.0",
            "Date": "Mon, 08 Apr 2024 19:37:02 GMT",
            "Content-Type": "application/json;charset=utf-8",
            "Content-Length": "2900",
            "Connection": "keep-alive",
            "X-Request-Id": "01htzk5h0p0stez4hcqym6s83d",
            "Strict-Transport-Security": "max-age=31536000"
        },
        "body": {
            "globalControls": {
                "timelineStartDate": "2024-04-08",
                "debug": true,
                "includeInputs": true,
                "resolution": [
                    "monthly",
                    "annual"
                ],
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "timelineDurationInYears": 1,
                "units": {
                    "monetary": "USD",
                    "electricity": "MBtu",
                    "naturalGas": "MBtu",
                    "woodPellets": "MBtu",
                    "propane": "MBtu",
                    "coal": "metric ton",
                    "emissions": "CO2",
                    "woodCord": "MBtu",
                    "energyStandard": "MBtu",
                    "fuelOil": "MBtu"
                }
            },
            "addressFull": "32861 E Carteret Ct, Millsboro, DE 19966-4829",
            "baseBuilding": {
                "systems": {
                    "waterHeating": {
                        "waterHeatingSystems": []
                    },
                    "hvac": {
                        "hvacHeatingSystems": [],
                        "hvacCoolingSystems": [
                            {
                                "coolEfficiencyUnits": "SEER",
                                "coolLoadFraction": 1.0,
                                "coolEfficiency": 18.0,
                                "systemType": "central air conditioner",
                                "id": "cooling-systems-1",
                                "compressorType": "single stage"
                            }
                        ]
                    }
                },
                "enclosure": {
                    "airInfiltration": {
                        "rate": 886,
                        "rateUnit": "CFM"
                    },
                    "walls": [
                        {
                            "assemblyEffectiveRValue": 19,
                            "id": "wall-insulation-1"
                        }
                    ],
                    "foundations": [
                        {
                            "type": "crawl vented",
                            "id": "floor-and-foundation-insulation-1"
                        },
                        {
                            "type": "crawl vented",
                            "id": "floor-and-foundation-insulation-2"
                        }
                    ],
                    "attics": [
                        {
                            "floorAssemblyEffectiveRValue": 30,
                            "id": "attic-insulation-1"
                        }
                    ]
                },
                "buildingSummary": {
                    "conditionedFloorArea": 2400,
                    "yearBuilt": 1982,
                    "bedroomsCount": 3,
                    "averageCeilingHeight": 10
                }
            },
            "addressComponents": {
                "zipCode": "19966-4829",
                "addressLine1": "32861 E Carteret Ct",
                "stateAbbreviation": "DE",
                "city": "Millsboro"
            },
            "errors": [
                {
                    "message": "\"+ node ./dist/cli-generate-hpxml-files.js --rowPath /tmp/modeling-api/hpxml-gen-inputs/01htzk5h0p0stez4hcqym6s83d/146161616_modified.json --outputDir /tmp/modeling-api/hpxml-gen-outputs/NORMAL/01htzk5h0p0stez4hcqym6s83d --dataVersion radiantV5 --defaultsVersion 2.4.0 --hpxmlVersion 3.0.0 --modelingInputsPath /tmp/modeling-api/hpxml-gen-inputs/01htzk5h0p0stez4hcqym6s83d/146161616_modeling_inputs.json --packageIds AUTOMATED_MEASURES --automatedMeasuresPath /tmp/modeling-api/hpxml-gen-inputs/01htzk5h0p0stez4hcqym6s83d/146161616_automated_measures.json --disableSchematron --debug\\n{\\\"code\\\":3,\\\"error\\\":\\\"Row is missing a required value for: YEAR_BUILT\\\",\\\"stack\\\":\\\"Error: Row is missing a required value for: YEAR_BUILT\\\\n    at /app/dist/utils/check-incoming-required-values.js:20:19\\\\n    at /app/node_modules/lodash/lodash.js:4967:15\\\\n    at baseForOwn (/app/node_modules/lodash/lodash.js:3032:24)\\\\n    at /app/node_modules/lodash/lodash.js:4936:18\\\\n    at Function.forEach (/app/node_modules/lodash/lodash.js:9410:14)\\\\n    at checkIncomingRequiredValues (/app/dist/utils/check-incoming-required-values.js:18:22)\\\\n    at genRadiantV5Hpxml300Defaults240 (/app/dist/generate-hpxml/radiantV5-hpxml300-defaults240/index.js:31:70)\\\\n    at generateHpxml (/app/dist/generate-hpxml/index.js:25:89)\\\\n    at generateHpxmlAndSaveToFile (/app/dist/cli-generate-hpxml-files.js:100:67)\\\\n    at /app/dist/cli-generate-hpxml-files.js:174:5\\\"}\"",
                    "code": "error-generating-hpxml"
                }
            ]
        }
    }
}

**Comment by kloconnell** [comment]
@lukeduran This error is related to a similar issue that was identified in tickets #27 and #48. This underlying issue is one of the major components of our v2.0.0 release, which has a lot of ramifying effects. In this specific example, the `yearBuilt` that you have reported is not being correctly mapped to the `appliedBaseBuilding` and as a result, since that characteristic is missing in our vendor data, we are getting an error. Tagging this with the v2.0.0 release candidate!

**Comment by kloconnell** [comment]
This request is now passing in the v2.0.0 environment.

@lukeduran I do want to call attention to one thing I noticed in this request. I see ``"hvacHeatingSystems": [],`` and ``"waterHeatingSystems": []``. This syntax indicates that there is no HVAC heating system and no water heating system. Please see this section of our documentation for additional context: https://docs.radiantlabs.co/projects/modeling-api/en/latest/usage.html#advanced-request. Since this house is in DE, I'm assuming there is likely a heating system and you likely just don't have information on that system. If this is the case, I would recommend either removing these objects from your request entirely, or marking them as ``null``, instead of an empty array.
