### ISSUE TITLE
Multiple cooling systems found attached to distribution system

### ISSUE THREAD

**Issue by lukeduran** [RadiantLabs/modeling-api-docs#60]
In this case, we didn't provide more than one of a single object type (i.e cooling system); however, we did include both a cooling system and a heat pump. I think this must be happening at the `appliedBaseHome` step.

**Example**

```
{
    "request": {
        "headers": {
            "User-Agent": "python-requests/2.28.1",
            "Accept-Encoding": "gzip, deflate",
            "Accept": "*/*",
            "Connection": "keep-alive",
            "Content-Type": "application/json",
            "Authorization": "Bearer jqnTR0wR6nmnS6u5mLEm1NSXq1kHSaF16LYlInbQ8tC04QHa",
            "Content-Length": "1567"
        },
        "body": {
            "addressFull": "2945 Beau Mont Farm Rd, Charlottesville, VA 22901-8717",
            "addressComponents": {
                "addressLine1": "2945 Beau Mont Farm Rd",
                "city": "Charlottesville",
                "stateAbbreviation": "VA",
                "zipCode": "22901-8717"
            },
            "baseBuilding": {
                "buildingSummary": {
                    "yearBuilt": 1999,
                    "bedroomsCount": 4,
                    "averageCeilingHeight": 8,
                    "conditionedFloorArea": 4144
                },
                "enclosure": {
                    "airInfiltration": {
                        "rate": 3729,
                        "rateUnit": "CFM"
                    },
                    "attics": [
                        {
                            "floorAssemblyEffectiveRValue": 21,
                            "id": "attic-insulation-1"
                        }
                    ]
                },
                "appliances": {
                    "clothesDryers": [
                        {
                            "fuel": "electricity",
                            "id": "clothes-dryer-1"
                        }
                    ]
                },
                "systems": {
                    "hvac": {
                        "hvacHeatingSystems": [],
                        "hvacCoolingSystems": [
                            {
                                "systemType": "central air conditioner",
                                "coolLoadFraction": 0.6,
                                "coolEfficiency": 16.0,
                                "coolEfficiencyUnits": "SEER",
                                "compressorType": "single stage",
                                "id": "cooling-systems-1"
                            }
                        ],
                        "hvacHeatPumps": [
                            {
                                "systemType": "air-to-air",
                                "heatLoadFraction": 0.4,
                                "coolLoadFraction": 0.4,
                                "heatEfficiency": 9.6,
                                "coolEfficiency": 18.0,
                                "compressorType": "variable speed",
                                "backupSystem": {},
                                "id": "heat-pump-systems-1"
                            }
                        ]
                    },
                    "waterHeating": {
                        "waterHeatingSystems": []
                    }
                }
            },
            "globalControls": {
                "debug": true,
                "includeInputs": true,
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "resolution": [
                    "annual",
                    "monthly"
                ],
                "timelineStartDate": "2024-04-08",
                "timelineDurationInYears": 1,
                "units": {
                    "energyStandard": "MBtu",
                    "coal": "metric ton",
                    "electricity": "MBtu",
                    "fuelOil": "MBtu",
                    "naturalGas": "MBtu",
                    "propane": "MBtu",
                    "woodCord": "MBtu",
                    "woodPellets": "MBtu",
                    "monetary": "USD",
                    "emissions": "CO2"
                }
            }
        }
    },
    "response": {
        "headers": {
            "Server": "nginx/1.24.0",
            "Date": "Mon, 08 Apr 2024 19:41:56 GMT",
            "Content-Type": "application/json;charset=utf-8",
            "Content-Length": "3562",
            "Connection": "keep-alive",
            "X-Request-Id": "01htzke9p98sp2c5kvv579e4j5",
            "Strict-Transport-Security": "max-age=31536000"
        },
        "body": {
            "globalControls": {
                "timelineStartDate": "2024-04-08",
                "debug": true,
                "includeInputs": true,
                "resolution": [
                    "monthly",
                    "annual"
                ],
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "timelineDurationInYears": 1,
                "units": {
                    "monetary": "USD",
                    "electricity": "MBtu",
                    "naturalGas": "MBtu",
                    "woodPellets": "MBtu",
                    "propane": "MBtu",
                    "coal": "metric ton",
                    "emissions": "CO2",
                    "woodCord": "MBtu",
                    "energyStandard": "MBtu",
                    "fuelOil": "MBtu"
                }
            },
            "addressFull": "2945 Beau Mont Farm Rd, Charlottesville, VA 22901-8717",
            "baseBuilding": {
                "systems": {
                    "waterHeating": {
                        "waterHeatingSystems": []
                    },
                    "hvac": {
                        "hvacHeatingSystems": [],
                        "hvacHeatPumps": [
                            {
                                "heatLoadFraction": 0.4,
                                "heatEfficiency": 9.6,
                                "backupSystem": {},
                                "coolLoadFraction": 0.4,
                                "coolEfficiency": 18.0,
                                "systemType": "air-to-air",
                                "id": "heat-pump-systems-1",
                                "compressorType": "variable speed"
                            }
                        ],
                        "hvacCoolingSystems": [
                            {
                                "coolEfficiencyUnits": "SEER",
                                "coolLoadFraction": 0.6,
                                "coolEfficiency": 16.0,
                                "systemType": "central air conditioner",
                                "id": "cooling-systems-1",
                                "compressorType": "single stage"
                            }
                        ]
                    }
                },
                "appliances": {
                    "clothesDryers": [
                        {
                            "fuel": "electricity",
                            "id": "clothes-dryer-1"
                        }
                    ]
                },
                "enclosure": {
                    "airInfiltration": {
                        "rate": 3729,
                        "rateUnit": "CFM"
                    },
                    "attics": [
                        {
                            "floorAssemblyEffectiveRValue": 21,
                            "id": "attic-insulation-1"
                        }
                    ]
                },
                "buildingSummary": {
                    "conditionedFloorArea": 4144,
                    "yearBuilt": 1999,
                    "bedroomsCount": 4,
                    "averageCeilingHeight": 8
                }
            },
            "addressComponents": {
                "zipCode": "22901-8717",
                "addressLine1": "2945 Beau Mont Farm Rd",
                "stateAbbreviation": "VA",
                "city": "Charlottesville"
            },
            "errors": [
                {
                    "message": "[\"Warning: No dishwasher specified, the model will not include dishwasher energy use.\" \"Error: Multiple cooling systems found attached to distribution system 'HVACAirDistributionASHP1'.\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/hpxml.rb:3034:in `hvac_systems'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/hpxml.rb:5126:in `block in check_for_errors'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/hpxml.rb:5125:in `each'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/hpxml.rb:5125:in `check_for_errors'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/measure.rb:158:in `validate_hpxml'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/measure.rb:112:in `run'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:289:in `run_measure'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:147:in `block (2 levels) in apply_measures'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:139:in `each'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:139:in `block in apply_measures'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:134:in `each'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:134:in `apply_measures'\" \"/var/bin/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/meta_measure.rb:22:in `run_hpxml_workflow'\" \"/var/bin/OpenStudio-HPXML/workflow/run_simulation.rb:40:in `run_workflow'\" \"/var/bin/OpenStudio-HPXML/workflow/run_simulation.rb:157:in `<top (required)>'\" \"eval:121:in `require'\" \"eval:121:in `require'\" \":/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'\" \":/openstudio_cli.rb:1518:in `execute'\" \":/openstudio_cli.rb:761:in `execute'\" \":/openstudio_cli.rb:1755:in `<main>'\" \"eval:175:in `eval'\" \"eval:175:in `require_embedded_absolute'\" \"eval:160:in `block in require_embedded'\" \"eval:154:in `each'\" \"eval:154:in `require_embedded'\" \"eval:113:in `require'\" \"eval:3:in `<main>'\"]",
                    "code": "openstudio-creating-input-unsuccessful"
                }
            ]
        }
    }
}
```

**Comment by kloconnell** [comment]
@lukeduran this is due to the current limitation of single systems. Though there is only 1 heat pump and 1 cooling system defined, our current defaulting engine is also limited to 1 distribution system. Unfortunately, a single distribution system can have only one source of heating and one source of cooling. In other words, a distribution system can be shared between a central air conditioner and a furnace, but not shared with a heat pump. When we release support for multiple systems, we will also include support for multiple distribution systems. Our apologies for the inconvenience.

**Comment by lukeduran** [comment]
Got it, thank you @kellyatradiantlabs! So for the time being, we will need to provide either the cooling system OR the heat pump, but not both? Is that correct?

**Comment by kloconnell** [comment]
~~Since this is related to the distribution system, I believe that if the cooling system or the heat pump did not have a distribution system, then it may be able to pass. For example, a room AC with an air-to-air heat pump or a central AC with a mini-split heat pump may work. In the first case, any heating system installed also could not have a distribution system.~~

**Comment by kloconnell** [comment]
Actually @lukeduran, after looking at #61, I need to rephrase my last response. Until we release support for multiple systems, my recommendation for the most reliable results is to only specify a single system providing cooling and a single system providing heating, regardless of their distribution types.
