### ISSUE TITLE
Validation and\/or XML Path Failure(s) - See individual packages for more information

### ISSUE THREAD

**Issue by lukeduran** [RadiantLabs/modeling-api-docs#61]
I've only seen this once, but figured I should surface it.

**Example**

```
{
    "request": {
        "headers": {
            "User-Agent": "python-requests/2.28.1",
            "Accept-Encoding": "gzip, deflate",
            "Accept": "*/*",
            "Connection": "keep-alive",
            "Content-Type": "application/json",
            "Authorization": "Bearer jqnTR0wR6nmnS6u5mLEm1NSXq1kHSaF16LYlInbQ8tC04QHa",
            "Content-Length": "1898"
        },
        "body": {
            "addressFull": "112 Summit Ave, Montclair, NJ 07043-2223",
            "addressComponents": {
                "addressLine1": "112 Summit Ave",
                "city": "Montclair",
                "stateAbbreviation": "NJ",
                "zipCode": "07043-2223"
            },
            "baseBuilding": {
                "buildingSummary": {
                    "yearBuilt": 1925,
                    "bedroomsCount": 4,
                    "averageCeilingHeight": 8,
                    "conditionedFloorArea": 3094
                },
                "enclosure": {
                    "airInfiltration": {
                        "rate": 4335,
                        "rateUnit": "CFM"
                    },
                    "attics": [
                        {
                            "floorAssemblyEffectiveRValue": 60,
                            "id": "attic-insulation-1"
                        },
                        {
                            "floorAssemblyEffectiveRValue": 22,
                            "id": "attic-insulation-2"
                        },
                        {
                            "floorAssemblyEffectiveRValue": 19,
                            "id": "attic-insulation-3"
                        }
                    ],
                    "foundations": [
                        {
                            "type": "basement unconditioned",
                            "id": "floor-and-foundation-insulation-1"
                        }
                    ],
                    "walls": [
                        {
                            "assemblyEffectiveRValue": 13,
                            "id": "wall-insulation-1"
                        },
                        {
                            "assemblyEffectiveRValue": 20,
                            "id": "wall-insulation-3"
                        }
                    ]
                },
                "systems": {
                    "hvac": {
                        "hvacHeatingSystems": [
                            {
                                "systemType": "boiler",
                                "fuel": "natural gas",
                                "heatLoadFraction": 0.9,
                                "heatEfficiency": 0.835,
                                "heatEfficiencyUnits": "AFUE",
                                "id": "heating-systems-1"
                            }
                        ],
                        "hvacCoolingSystems": [
                            {
                                "systemType": "central air conditioner",
                                "coolLoadFraction": 0.6,
                                "coolEfficiency": 16.0,
                                "coolEfficiencyUnits": "SEER",
                                "id": "cooling-systems-1"
                            }
                        ],
                        "hvacHeatPumps": [
                            {
                                "systemType": "mini-split",
                                "heatLoadFraction": 0.1,
                                "coolLoadFraction": 0.4,
                                "heatEfficiency": 7.7,
                                "coolEfficiency": 13.0,
                                "backupSystem": {},
                                "id": "heat-pump-systems-1"
                            }
                        ]
                    },
                    "waterHeating": {
                        "waterHeatingSystems": []
                    }
                }
            },
            "globalControls": {
                "debug": true,
                "includeInputs": true,
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "resolution": [
                    "annual",
                    "monthly"
                ],
                "timelineStartDate": "2024-04-08",
                "timelineDurationInYears": 1,
                "units": {
                    "energyStandard": "MBtu",
                    "coal": "metric ton",
                    "electricity": "MBtu",
                    "fuelOil": "MBtu",
                    "naturalGas": "MBtu",
                    "propane": "MBtu",
                    "woodCord": "MBtu",
                    "woodPellets": "MBtu",
                    "monetary": "USD",
                    "emissions": "CO2"
                }
            }
        }
    },
    "response": {
        "headers": {
            "Server": "nginx/1.24.0",
            "Date": "Mon, 08 Apr 2024 20:06:58 GMT",
            "Content-Type": "application/json;charset=utf-8",
            "Content-Length": "2842",
            "Connection": "keep-alive",
            "X-Request-Id": "01htzmxct7z0smm7y48w043kx6",
            "Strict-Transport-Security": "max-age=31536000"
        },
        "body": {
            "globalControls": {
                "timelineStartDate": "2024-04-08",
                "debug": true,
                "includeInputs": true,
                "resolution": [
                    "monthly",
                    "annual"
                ],
                "includeBase": true,
                "includeTypical": true,
                "useFixture": false,
                "timelineDurationInYears": 1,
                "units": {
                    "monetary": "USD",
                    "electricity": "MBtu",
                    "naturalGas": "MBtu",
                    "woodPellets": "MBtu",
                    "propane": "MBtu",
                    "coal": "metric ton",
                    "emissions": "CO2",
                    "woodCord": "MBtu",
                    "energyStandard": "MBtu",
                    "fuelOil": "MBtu"
                }
            },
            "addressFull": "112 Summit Ave, Montclair, NJ 07043-2223",
            "baseBuilding": {
                "systems": {
                    "waterHeating": {
                        "waterHeatingSystems": []
                    },
                    "hvac": {
                        "hvacHeatingSystems": [
                            {
                                "heatLoadFraction": 0.9,
                                "heatEfficiency": 0.835,
                                "fuel": "natural gas",
                                "systemType": "boiler",
                                "id": "heating-systems-1",
                                "heatEfficiencyUnits": "AFUE"
                            }
                        ],
                        "hvacHeatPumps": [
                            {
                                "heatLoadFraction": 0.1,
                                "heatEfficiency": 7.7,
                                "backupSystem": {},
                                "coolLoadFraction": 0.4,
                                "coolEfficiency": 13.0,
                                "systemType": "mini-split",
                                "id": "heat-pump-systems-1"
                            }
                        ],
                        "hvacCoolingSystems": [
                            {
                                "coolEfficiencyUnits": "SEER",
                                "coolLoadFraction": 0.6,
                                "coolEfficiency": 16.0,
                                "systemType": "central air conditioner",
                                "id": "cooling-systems-1"
                            }
                        ]
                    }
                },
                "enclosure": {
                    "airInfiltration": {
                        "rate": 4335,
                        "rateUnit": "CFM"
                    },
                    "walls": [
                        {
                            "assemblyEffectiveRValue": 13,
                            "id": "wall-insulation-1"
                        },
                        {
                            "assemblyEffectiveRValue": 20,
                            "id": "wall-insulation-3"
                        }
                    ],
                    "foundations": [
                        {
                            "type": "basement unconditioned",
                            "id": "floor-and-foundation-insulation-1"
                        }
                    ],
                    "attics": [
                        {
                            "floorAssemblyEffectiveRValue": 60,
                            "id": "attic-insulation-1"
                        },
                        {
                            "floorAssemblyEffectiveRValue": 22,
                            "id": "attic-insulation-2"
                        },
                        {
                            "floorAssemblyEffectiveRValue": 19,
                            "id": "attic-insulation-3"
                        }
                    ]
                },
                "buildingSummary": {
                    "conditionedFloorArea": 3094,
                    "yearBuilt": 1925,
                    "bedroomsCount": 4,
                    "averageCeilingHeight": 8
                }
            },
            "addressComponents": {
                "zipCode": "07043-2223",
                "addressLine1": "112 Summit Ave",
                "stateAbbreviation": "NJ",
                "city": "Montclair"
            },
            "errors": [
                {
                    "message": "\"+ node ./dist/cli-generate-hpxml-files.js --rowPath /tmp/modeling-api/hpxml-gen-inputs/01htzmxct7z0smm7y48w043kx6/199423397_modified.json --outputDir /tmp/modeling-api/hpxml-gen-outputs/NORMAL/01htzmxct7z0smm7y48w043kx6 --dataVersion radiantV5 --defaultsVersion 2.4.0 --hpxmlVersion 3.0.0 --modelingInputsPath /tmp/modeling-api/hpxml-gen-inputs/01htzmxct7z0smm7y48w043kx6/199423397_modeling_inputs.json --packageIds AUTOMATED_MEASURES --automatedMeasuresPath /tmp/modeling-api/hpxml-gen-inputs/01htzmxct7z0smm7y48w043kx6/199423397_automated_measures.json --disableSchematron --debug\\n{\\\"code\\\":3,\\\"error\\\":\\\"Validation and/or XML Path Failure(s) - See individual packages for more information\\\",\\\"stack\\\":\\\"Error: Validation and/or XML Path Failure(s) - See individual packages for more information\\\\n    at checkPreModelingPackagesForErrors (/app/dist/utils/check-pre-modeling-packages-for-errors.js:14:15)\\\\n    at generateHpxmlAndSaveToFile (/app/dist/cli-generate-hpxml-files.js:106:62)\\\"}\"",
                    "code": "error-generating-hpxml"
                }
            ]
        }
    }
}
```

**Comment by kloconnell** [comment]
In v2.0.0, the error associated with this ticket has been clarified below. This error is due to the lack of support for multiple systems.
```
    "errors": [
        {
            "message": "The OpenStudio process failed",
            "code": "openstudio-failed",
            "data": {
                "errors": [
                    "Expected 1 or more element(s) for xpath: ../../HVACDistribution/DistributionSystemType/AirDistribution/AirDistributionType[text()=\"regular velocity\"] | ../../HVACDistribution/DistributionSystemType/Other[text()=\"DSE\"] [context: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType=\"central air conditioner\"], id: \"cooling-systems-1\"]",
                    "Expected 1 element(s) for xpath: DistributionSystem [context: /HPXML/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem[CoolingSystemType=\"central air conditioner\"], id: \"cooling-systems-1\"]"
                ]
            }
        }
    ]
```
